name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to DigitalOcean
      run: |
        rsync -avz --delete --exclude='.git*' --exclude='.github*' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/apps/WeatherJournal
